/* Generated by the Nim Compiler v2.2.12 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI738197518 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078609 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078616 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555189 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555188 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555185 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555186 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
var NNI33555186 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555186.node = NNI33555186;
NTI33555188.base = NTI33555185;
NTI33555189.base = NTI33555185;
var NNI33555185 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555188, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555189, name: "up", sons: null}]};
NTI33555185.node = NNI33555185;
var NNI33555181 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555181.node = NNI33555181;
NTI33555185.base = NTI33555181;
NTI33555186.base = NTI33555185;
NTI134217749.base = NTI33555186;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555186;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555186;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555186;
var NNI973078616 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI973078609, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI973078616.node = NNI973078616;
var NNI738197518 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI738197518.node = NNI738197518;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557377 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2925(ti_p2))) {
      result_33557377 = src_p1;
      }
      else {
        result_33557377 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557377 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557377 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557377 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557377 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557377, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557377 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557377 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557377 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557377[i] = nimCopy(result_33557377[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557377 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557377 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557377[i] = nimCopy(result_33557377[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557377 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557377 = src_p1;
      break;
    }

  return result_33557377;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557490 = false;

  BeforeRet: {
    var x_33557491 = obj_p0;
    if ((x_33557491 == subclass_p1)) {
    result_33557490 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557491 == subclass_p1))) break Label2;
          if ((x_33557491 == null)) {
          result_33557490 = false;
          break BeforeRet;
          }
          
          x_33557491 = x_33557491.base;
        }
    };
    result_33557490 = true;
    break BeforeRet;
  };

  return result_33557490;

}

function toJSStr(s_p0) {
  var result_33556954 = null;

    var res_33557020 = newSeq__system_u2563((s_p0).length);
    var i_33557021 = 0;
    var j_33557022 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557021 < (s_p0).length)) break Label2;
          var c_33557023 = s_p0[i_33557021];
          if ((c_33557023 < 128)) {
          res_33557020[j_33557022] = String.fromCharCode(c_33557023);
          i_33557021 += 1;
          }
          else {
            var helper_33557049 = newSeq__system_u2563(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557050 = c_33557023.toString(16);
                  if ((((code_33557050) == null ? 0 : (code_33557050).length) == 1)) {
                  helper_33557049.push("%0");;
                  }
                  else {
                  helper_33557049.push("%");;
                  }
                  
                  helper_33557049.push(code_33557050);;
                  i_33557021 += 1;
                  if ((((s_p0).length <= i_33557021) || (s_p0[i_33557021] < 128))) {
                  break Label3;
                  }
                  
                  c_33557023 = s_p0[i_33557021];
                }
            };
++excHandler;
            try {
            res_33557020[j_33557022] = decodeURIComponent(helper_33557049.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557020[j_33557022] = helper_33557049.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557022 += 1;
        }
    };
    if (res_33557020.length < j_33557022) { for (var i = res_33557020.length ; i < j_33557022 ; ++i) res_33557020.push(null); }
               else { res_33557020.length = j_33557022; };
    result_33556954 = res_33557020.join("");

  return result_33556954;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557412 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557412 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557412;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557417 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557417 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557417;

}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557204 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557204 = Temporary1;
    break BeforeRet;
  };

  return result_33557204;

}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557200 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557200 = Temporary1;
    break BeforeRet;
  };

  return result_33557200;

}

function addChar(x_p0, c_p1) {
    x_p0.push(c_p1);

  
}
var objectID_1191182514 = [0];

function setTheme(theme_p0) {
    document.documentElement.setAttribute("data-theme", theme_p0);
    window.localStorage.setItem("theme", theme_p0);

  
}

function isFatPointer__system_u2925(ti_p0) {
  var result_33557359 = false;

  BeforeRet: {
    result_33557359 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557359;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_587203751 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_587203751 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_587203751;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_587203751 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_402653200 = [[]];

    result_402653200[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_402653200, 0, xHEX60gensym0_p0);

  return result_402653200[0];

}

function add__system_u1973(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2563(len_p0) {
  var result_33556999 = [];

    result_33556999 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556999[i] = null; }
  return result_33556999;

}

function isNimException__system_u2048() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556483 = null;

    if (isNimException__system_u2048()) {
    result_33556483 = lastJSError;
    }
    

  return result_33556483;

}

function raiseDefect() {
    if (isNimException__system_u2048()) {
    var e_33556699 = getCurrentException();
    if (isObj(e_33556699.m_type, NTI33555186)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556699);
    }
    
    throw e_33556699;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556693 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556693[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556693[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556693[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556693[0], [32,91]);;
    add__system_u1973(buf_33556693, 0, e_p0.name);
    nimAddStrStr(buf_33556693[0], [93,10]);;
    var cbuf_33556694 = toJSStr(buf_33556693[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556694);
  }
  else {
    throw cbuf_33556694;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal__stdZassertions_u46(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
    sysFatal__stdZassertions_u46(msg_p0);

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
    raiseAssert__stdZassertions_u44(msg_p0);

  
}

function onDOMLoaded(e_p0) {
            var Temporary4;

function HEX3Aanonymous__dochack_u65(event_p0) {
    event_p0.target.parentNode.style.display = "none";
    event_p0.target.parentNode.nextSibling.style.display = "inline";

  
}

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_587202624 = null;
      var colontmp__587203742 = [];
      colontmp__587203742 = document.getElementsByClassName("pragmadots");
      var i_587203744 = 0;
      var L_587203745 = (colontmp__587203742).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203744 < L_587203745)) break Label3;
            pragmaDots_587202624 = colontmp__587203742[chckIndx(i_587203744, 0, (colontmp__587203742).length - 1)];
            Temporary4 = HEX3Aanonymous__dochack_u65.bind(null); Temporary4.ClP_0 = HEX3Aanonymous__dochack_u65; Temporary4.ClE_0 = null;
            pragmaDots_587202624.onclick = Temporary4;
            i_587203744 += 1;
            if (!(((colontmp__587203742).length == L_587203745))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function isWhitespace__dochack_u392(x_p0) {
  var result_587202954 = false;

    result_587202954 = (((x_p0.nodeName == "#text") && !/\S/.test(x_p0.textContent)) || (x_p0.nodeName == "#comment"));

  return result_587202954;

}

function toToc__dochack_u395(x_p0, father_p1) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_p0.nodeName == "UL")) {
    var f_587202965 = {heading: null, kids: [], sortId: (father_p1.kids).length, doSort: false};
    var i_587202966 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_587202966 < x_p0.childNodes.length)) break Label2;
          var nxt_587202967 = addInt(i_587202966, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_587202967 < x_p0.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace__dochack_u392(x_p0.childNodes[nxt_587202967]);                }              if (!Temporary5) break Label4;
                nxt_587202967 = addInt(nxt_587202967, 1);
              }
          };
            if (!(nxt_587202967 < x_p0.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_p0.childNodes[i_587202966].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_p0.childNodes[i_587202966].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_p0.childNodes[nxt_587202967].nodeName == "UL");            }          if (Temporary6) {
          var e_587202980 = {heading: x_p0.childNodes[i_587202966].childNodes[0], kids: [], sortId: (f_587202965.kids).length, doSort: false};
          var it_587202981 = x_p0.childNodes[nxt_587202967];
          Label9: {
            var j_587202986 = 0;
            var colontmp__587203759 = 0;
            colontmp__587203759 = it_587202981.childNodes.length;
            var i_587203760 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_587203760 < colontmp__587203759)) break Label11;
                  j_587202986 = i_587203760;
                  toToc__dochack_u395(it_587202981.childNodes[j_587202986], e_587202980);
                  i_587203760 = addInt(i_587203760, 1);
                }
            };
          };
          f_587202965.kids.push(e_587202980);;
          i_587202966 = addInt(nxt_587202967, 1);
          }
          else {
            toToc__dochack_u395(x_p0.childNodes[i_587202966], f_587202965);
            i_587202966 = addInt(i_587202966, 1);
          }
          
        }
    };
    father_p1.kids.push(f_587202965);;
    }
    else {
    if (isWhitespace__dochack_u392(x_p0)) {
    }
    else {
    if ((x_p0.nodeName == "LI")) {
    var idx_587203004 = [];
    Label12: {
      var i_587203009 = 0;
      var colontmp__587203763 = 0;
      colontmp__587203763 = x_p0.childNodes.length;
      var i_587203764 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_587203764 < colontmp__587203763)) break Label14;
            i_587203009 = i_587203764;
            if (!(isWhitespace__dochack_u392(x_p0.childNodes[i_587203009]))) {
            idx_587203004.push(i_587203009);;
            }
            
            i_587203764 = addInt(i_587203764, 1);
          }
      };
    };
      if (!((idx_587203004).length == 2)) Temporary15 = false; else {        Temporary15 = (x_p0.childNodes[idx_587203004[chckIndx(1, 0, (idx_587203004).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_587203025 = {heading: x_p0.childNodes[idx_587203004[chckIndx(0, 0, (idx_587203004).length - 1)]], kids: [], sortId: (father_p1.kids).length, doSort: false};
    var it_587203026 = x_p0.childNodes[idx_587203004[chckIndx(1, 0, (idx_587203004).length - 1)]];
    Label16: {
      var j_587203031 = 0;
      var colontmp__587203767 = 0;
      colontmp__587203767 = it_587203026.childNodes.length;
      var i_587203768 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_587203768 < colontmp__587203767)) break Label18;
            j_587203031 = i_587203768;
            toToc__dochack_u395(it_587203026.childNodes[j_587203031], e_587203025);
            i_587203768 = addInt(i_587203768, 1);
          }
      };
    };
    father_p1.kids.push(e_587203025);;
    }
    else {
      Label19: {
        var i_587203040 = 0;
        var colontmp__587203771 = 0;
        colontmp__587203771 = x_p0.childNodes.length;
        var i_587203772 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_587203772 < colontmp__587203771)) break Label21;
              i_587203040 = i_587203772;
              toToc__dochack_u395(x_p0.childNodes[i_587203040], father_p1);
              i_587203772 = addInt(i_587203772, 1);
            }
        };
      };
    }
    
    }
    else {
    father_p1.kids.push({heading: x_p0, kids: [], sortId: (father_p1.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems__dochack_u183(x_p0, heading_p1, items_p2, items_p2_Idx) {
  BeforeRet: {
    if ((x_p0 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_p0.heading == null)) && (x_p0.heading.textContent == heading_p1))) {
    Label1: {
      var i_587202763 = 0;
      var colontmp__587203775 = 0;
      colontmp__587203775 = (x_p0.kids).length;
      var i_587203776 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203776 < colontmp__587203775)) break Label3;
            i_587202763 = i_587203776;
            items_p2[items_p2_Idx].push(x_p0.kids[chckIndx(i_587202763, 0, (x_p0.kids).length - 1)].heading);;
            i_587203776 = addInt(i_587203776, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_587202789 = null;
        var i_587203780 = 0;
        var L_587203781 = (x_p0.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_587203780 < L_587203781)) break Label6;
              k_587202789 = x_p0.kids[chckIndx(i_587203780, 0, (x_p0.kids).length - 1)];
              extractItems__dochack_u183(k_587202789, heading_p1, items_p2, items_p2_Idx);
              i_587203780 += 1;
              if (!(((x_p0.kids).length == L_587203781))) {
              failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree__dochack_u114(tag_p0, kids_p1) {
  var result_587202677 = null;

    result_587202677 = document.createElement(tag_p0);
    Label1: {
      var k_587202691 = null;
      var i_587203793 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203793 < (kids_p1).length)) break Label3;
            k_587202691 = kids_p1[chckIndx(i_587203793, 0, (kids_p1).length - 1)];
            result_587202677.appendChild(k_587202691);
            i_587203793 += 1;
          }
      };
    };

  return result_587202677;

}

function text__dochack_u139(s_p0) {
  var result_587202701 = null;

    result_587202701 = document.createTextNode(s_p0);

  return result_587202701;

}

function uncovered__dochack_u568(x_p0) {
    var Temporary1;

  var result_587203130 = null;

  BeforeRet: {
    if ((((x_p0.kids).length == 0) && !((x_p0.heading == null)))) {
    if (!(x_p0.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_p0;
    }
    else {
    Temporary1 = null;
    }
    
    result_587203130 = Temporary1;
    break BeforeRet;
    }
    
    result_587203130 = {heading: x_p0.heading, kids: [], sortId: x_p0.sortId, doSort: x_p0.doSort};
    Label2: {
      var k_587203145 = null;
      var i_587203800 = 0;
      var L_587203801 = (x_p0.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_587203800 < L_587203801)) break Label4;
            k_587203145 = x_p0.kids[chckIndx(i_587203800, 0, (x_p0.kids).length - 1)];
            var y_587203146 = uncovered__dochack_u568(k_587203145);
            if (!((y_587203146 == null))) {
            result_587203130.kids.push(y_587203146);;
            }
            
            i_587203800 += 1;
            if (!(((x_p0.kids).length == L_587203801))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_587203130.kids).length == 0)) {
    result_587203130 = null;
    }
    
  };

  return result_587203130;

}

function mergeTocs__dochack_u598(orig_p0, news_p1) {
  var result_587203161 = null;

    result_587203161 = uncovered__dochack_u568(orig_p0);
    if ((result_587203161 == null)) {
    result_587203161 = news_p1;
    }
    else {
      Label1: {
        var i_587203173 = 0;
        var colontmp__587203796 = 0;
        colontmp__587203796 = (news_p1.kids).length;
        var i_587203797 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_587203797 < colontmp__587203796)) break Label3;
              i_587203173 = i_587203797;
              result_587203161.kids.push(news_p1.kids[chckIndx(i_587203173, 0, (news_p1.kids).length - 1)]);;
              i_587203797 = addInt(i_587203797, 1);
            }
        };
      };
    }
    

  return result_587203161;

}

function buildToc__dochack_u618(orig_p0, types_p1, procs_p2) {
  var result_587203182 = null;

    var newStuff_587203187 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_587203191 = null;
      var i_587203788 = 0;
      var L_587203789 = (types_p1).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203788 < L_587203789)) break Label3;
            t_587203191 = types_p1[chckIndx(i_587203788, 0, (types_p1).length - 1)];
            var c_587203196 = {heading: t_587203191.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_587203191.__karaxMarker__ = true;
            Label4: {
              var p_587203200 = null;
              var i_587203785 = 0;
              var L_587203786 = (procs_p2).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_587203785 < L_587203786)) break Label6;
                    p_587203200 = procs_p2[chckIndx(i_587203785, 0, (procs_p2).length - 1)];
                    if (!(p_587203200.hasOwnProperty('__karaxMarker__'))) {
                    var xx_587203201 = p_587203200.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_587203201).length == 1) && (xx_587203201[chckIndx(0, 0, (xx_587203201).length - 1)].textContent == t_587203191.textContent))) {
                    var q_587203206 = tree__dochack_u114("A", [text__dochack_u139(p_587203200.title)]);
                    q_587203206.setAttribute("href", p_587203200.getAttribute("href"));
                    c_587203196.kids.push({heading: q_587203206, kids: [], sortId: 0, doSort: false});;
                    p_587203200.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_587203785 += 1;
                    if (!(((procs_p2).length == L_587203786))) {
                    failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_587203187.kids.push(c_587203196);;
            i_587203788 += 1;
            if (!(((types_p1).length == L_587203789))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_587203182 = mergeTocs__dochack_u598(orig_p0, newStuff_587203187);

  return result_587203182;

}

function add__dochack_u132(parent_p0, kid_p1) {
    if (((parent_p0.nodeName == "TR") && ((kid_p1.nodeName == "TD") || (kid_p1.nodeName == "TH")))) {
    var k_587202695 = document.createElement("TD");
    k_587202695.appendChild(kid_p1);
    parent_p0.appendChild(k_587202695);
    }
    else {
    parent_p0.appendChild(kid_p1);
    }
    

  
}

function setClass__dochack_u136(e_p0, value_p1) {
    e_p0.setAttribute("class", value_p1);

  
}

function toHtml__dochack_u262(x_p0, isRoot_p1) {
    var Temporary1;

function HEX3Aanonymous__dochack_u282(a_p0, b_p1) {
  var result_587202845 = 0;

  BeforeRet: {
    if ((!((a_p0.heading == null)) && !((b_p1.heading == null)))) {
    var x_587202854 = a_p0.heading.textContent;
    var y_587202855 = b_p1.heading.textContent;
    if ((x_587202854 < y_587202855)) {
    result_587202845 = (-1);
    break BeforeRet;
    }
    
    if ((y_587202855 < x_587202854)) {
    result_587202845 = 1;
    break BeforeRet;
    }
    
    result_587202845 = 0;
    break BeforeRet;
    }
    else {
      result_587202845 = subInt(a_p0.sortId, b_p1.sortId);
      break BeforeRet;
    }
    
  };

  return result_587202845;

}

  var result_587202825 = null;

  BeforeRet: {
    if ((x_p0 == null)) {
    result_587202825 = null;
    break BeforeRet;
    }
    
    if (((x_p0.kids).length == 0)) {
    if ((x_p0.heading == null)) {
    result_587202825 = null;
    break BeforeRet;
    }
    
    result_587202825 = x_p0.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_587202825 = tree__dochack_u114("DIV", []);
    if ((!((x_p0.heading == null)) && !(x_p0.heading.hasOwnProperty('__karaxMarker__')))) {
    add__dochack_u132(result_587202825, x_p0.heading.cloneNode(true));
    }
    
    var ul_587202841 = tree__dochack_u114("UL", []);
    if (isRoot_p1) {
    setClass__dochack_u136(ul_587202841, "simple simple-toc");
    }
    else {
    setClass__dochack_u136(ul_587202841, "simple");
    }
    
    if (x_p0.doSort) {
    Temporary1 = HEX3Aanonymous__dochack_u282.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__dochack_u282; Temporary1.ClE_0 = null;
    x_p0.kids.sort(Temporary1);
    }
    
    Label2: {
      var k_587202867 = null;
      var i_587203804 = 0;
      var L_587203805 = (x_p0.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_587203804 < L_587203805)) break Label4;
            k_587202867 = x_p0.kids[chckIndx(i_587203804, 0, (x_p0.kids).length - 1)];
            var y_587202868 = toHtml__dochack_u262(k_587202867, false);
            if (!((y_587202868 == null))) {
            add__dochack_u132(ul_587202841, tree__dochack_u114("LI", [y_587202868]));
            }
            
            i_587203804 += 1;
            if (!(((x_p0.kids).length == L_587203805))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_587202841.childNodes.length == 0))) {
    add__dochack_u132(result_587202825, ul_587202841);
    }
    
    if ((result_587202825.childNodes.length == 0)) {
    result_587202825 = null;
    }
    
  };

  return result_587202825;

}

function replaceById__dochack_u142(id_p0, newTree_p1) {
    var x_587202705 = document.getElementById(id_p0);
    x_587202705.parentNode.replaceChild(newTree_p1, x_587202705);
    newTree_p1.id = id_p0;

  
}

function togglevis__dochack_u676(d_p0) {
    if ((d_p0.style.display == "none")) {
    d_p0.style.display = "inline";
    }
    else {
      d_p0.style.display = "none";
    }
    

  
}

function groupBy(value_p0) {
    var toc_587203240 = document.getElementById("toc-list");
    if ((alternative_587203235[0] == null)) {
    var tt_587203248 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc__dochack_u395(toc_587203240, tt_587203248);
    tt_587203248 = tt_587203248.kids[chckIndx(0, 0, (tt_587203248.kids).length - 1)];
    var types_587203253 = [[]];
    var procs_587203258 = [[]];
    extractItems__dochack_u183(tt_587203248, "Types", types_587203253, 0);
    extractItems__dochack_u183(tt_587203248, "Procs", procs_587203258, 0);
    extractItems__dochack_u183(tt_587203248, "Converters", procs_587203258, 0);
    extractItems__dochack_u183(tt_587203248, "Methods", procs_587203258, 0);
    extractItems__dochack_u183(tt_587203248, "Templates", procs_587203258, 0);
    extractItems__dochack_u183(tt_587203248, "Macros", procs_587203258, 0);
    extractItems__dochack_u183(tt_587203248, "Iterators", procs_587203258, 0);
    var ntoc_587203259 = buildToc__dochack_u618(tt_587203248, types_587203253[0], procs_587203258[0]);
    var x_587203260 = toHtml__dochack_u262(ntoc_587203259, true);
    alternative_587203235[0] = tree__dochack_u114("DIV", [x_587203260]);
    }
    
    if ((value_p0 == "type")) {
    replaceById__dochack_u142("tocRoot", alternative_587203235[0]);
    }
    else {
    replaceById__dochack_u142("tocRoot", tree__dochack_u114("DIV", []));
    }
    
    togglevis__dochack_u676(document.getElementById("toc-list"));

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function HEX5BHEX5D__pureZstrutils_u1308(s_p0, x_p1) {
  var result_754976033 = [];

    var a_754976035 = x_p1.a;
    var L_754976037 = addInt(subInt(subInt((s_p0).length, x_p1.b), a_754976035), 1);
    result_754976033 = nimCopy(null, mnewString(chckRange(L_754976037, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_754976042 = 0;
      var i_587203814 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203814 < L_754976037)) break Label3;
            i_754976042 = i_587203814;
            result_754976033[chckIndx(i_754976042, 0, (result_754976033).length - 1)] = s_p0[chckIndx(addInt(i_754976042, a_754976035), 0, (s_p0).length - 1)];
            i_587203814 = addInt(i_587203814, 1);
          }
      };
    };

  return result_754976033;

}

function HEX2EHEX2E__stdZenumutils_u105(a_p0, b_p1) {
  var result_973078640 = ({a: 0, b: 0});

    result_973078640 = nimCopy(result_973078640, {a: a_p0, b: b_p1}, NTI973078616);

  return result_973078640;

}
async function loadIndex__dochack_u896() {
  var result_587203458 = null;

  BeforeRet: {
    var indexURL_587203464 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_587203490 = HEX5BHEX5D__pureZstrutils_u1308(cstrToNimstr(indexURL_587203464), HEX2EHEX2E__stdZenumutils_u105(0, 14));
    var resp_587203502 = (await (await fetch(indexURL_587203464)).text());
    var indexElem_587203503 = document.createElement("div");
    indexElem_587203503.innerHTML = resp_587203502;
    Label1: {
      var href_587203525 = null;
      var colontmp__587203808 = [];
      colontmp__587203808 = indexElem_587203503.getElementsByClassName("reference");
      var i_587203810 = 0;
      var L_587203811 = (colontmp__587203808).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203810 < L_587203811)) break Label3;
            href_587203525 = colontmp__587203808[chckIndx(i_587203810, 0, (colontmp__587203808).length - 1)];
            href_587203525.setAttribute("href", toJSStr((rootURL_587203490).concat(cstrToNimstr(href_587203525.getAttribute("href")))));
            db_587203277[0].push(href_587203525);;
            contents_587203278[0].push(href_587203525.getAttribute("data-doc-search-tag"));;
            i_587203810 += 1;
            if (!(((colontmp__587203808).length == L_587203811))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_587203458 = undefined;
    break BeforeRet;
  };

  return result_587203458;

}

function then__dochack_u1059(future_p0, onSuccess_p1, onReject_p2) {
  var result_587203625 = null;

  BeforeRet: {
    var ret_587203635 = null;
    ret_587203635 = future_p0.then(onSuccess_p1, onReject_p2);
    result_587203625 = ret_587203635;
    break BeforeRet;
  };

  return result_587203625;

}

function nsuToLowerAsciiChar(c_p0) {
  var result_754974807 = 0;

    if ((ConstSet2[c_p0] != undefined)) {
    result_754974807 = (c_p0 ^ 32);
    }
    else {
      result_754974807 = c_p0;
    }
    

  return result_754974807;

}

function fuzzyMatch__fuzzysearch_u16(pattern_p0, str_p1) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_738197525 = {Field0: 0, Field1: false};

    var scoreState_738197526 = (-100);
    var headerMatched_738197527 = false;
    var unmatchedLeadingCharCount_738197528 = 0;
    var consecutiveMatchCount_738197529 = 0;
    var strIndex_738197530 = 0;
    var patIndex_738197531 = 0;
    var score_738197532 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_738197530 < ((str_p1) == null ? 0 : (str_p1).length)) && (patIndex_738197531 < ((pattern_p0) == null ? 0 : (pattern_p0).length)))) break Label2;
          Label3: {
            var patternChar_738197535 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(patIndex_738197531, 0, (pattern_p0).length - 1)));
            var strChar_738197536 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1)));
            if ((ConstSet3[patternChar_738197535] != undefined)) {
            patIndex_738197531 = addInt(patIndex_738197531, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_738197536] != undefined)) {
            strIndex_738197530 = addInt(strIndex_738197530, 1);
            break Label3;
            }
            
            if ((!(headerMatched_738197527) && (strChar_738197536 == 58))) {
            headerMatched_738197527 = true;
            scoreState_738197526 = (-100);
            score_738197532 = chckRange(Number(BigInt(Math.trunc(Math.floor((0.5 * score_738197532))))), (-2147483648), 2147483647);
            patIndex_738197531 = 0;
            strIndex_738197530 = addInt(strIndex_738197530, 1);
            break Label3;
            }
            
            if ((strChar_738197536 == patternChar_738197535)) {
            switch (scoreState_738197526) {
            case (-100):
            case 20:
              scoreState_738197526 = 10;
              break;
            case 0:
              scoreState_738197526 = 5;
              score_738197532 = addInt(score_738197532, scoreState_738197526);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_738197529 = addInt(consecutiveMatchCount_738197529, 1);
              scoreState_738197526 = 5;
              score_738197532 = addInt(score_738197532, mulInt(5, consecutiveMatchCount_738197529));
              if ((scoreState_738197526 == 10)) {
              score_738197532 = addInt(score_738197532, 10);
              }
              
              var onBoundary_738197588 = (patIndex_738197531 == ((pattern_p0) == null ? -1 : (pattern_p0).length - 1));
              if ((!(onBoundary_738197588) && (strIndex_738197530 < ((str_p1) == null ? -1 : (str_p1).length - 1)))) {
              var nextPatternChar_738197589 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(addInt(patIndex_738197531, 1), 0, (pattern_p0).length - 1)));
              var nextStrChar_738197590 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(addInt(strIndex_738197530, 1), 0, (str_p1).length - 1)));
              if (!!((ConstSet5[nextStrChar_738197590] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_738197590 == nextPatternChar_738197589));              }              onBoundary_738197588 = Temporary4;
              }
              
              if (onBoundary_738197588) {
              scoreState_738197526 = 20;
              score_738197532 = addInt(score_738197532, scoreState_738197526);
              }
              
              break;
            case (-1):
            case (-3):
              if (!((ConstSet6[str_p1.charCodeAt(chckIndx(subInt(strIndex_738197530, 1), 0, (str_p1).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_p1.charCodeAt(chckIndx(subInt(strIndex_738197530, 1), 0, (str_p1).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_738197614 = Temporary5;
              if (isLeadingChar_738197614) {
              scoreState_738197526 = 10;
              }
              else {
                scoreState_738197526 = 0;
                score_738197532 = addInt(score_738197532, scoreState_738197526);
              }
              
              break;
            }
            patIndex_738197531 = addInt(patIndex_738197531, 1);
            }
            else {
              switch (scoreState_738197526) {
              case (-100):
                scoreState_738197526 = (-3);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                break;
              case 5:
                scoreState_738197526 = (-1);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                consecutiveMatchCount_738197529 = 0;
                break;
              case (-3):
                if ((unmatchedLeadingCharCount_738197528 < 3)) {
                scoreState_738197526 = (-3);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                }
                
                unmatchedLeadingCharCount_738197528 = addInt(unmatchedLeadingCharCount_738197528, 1);
                break;
              default: 
                scoreState_738197526 = (-1);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                break;
              }
            }
            
            strIndex_738197530 = addInt(strIndex_738197530, 1);
          };
        }
    };
      if (!(patIndex_738197531 == ((pattern_p0) == null ? 0 : (pattern_p0).length))) Temporary7 = false; else {        if ((strIndex_738197530 == ((str_p1) == null ? 0 : (str_p1).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_738197532 = addInt(score_738197532, 10);
    }
    
    var colontmp__587203827 = nimMax(0, score_738197532);
    var colontmp__587203828 = (0 < score_738197532);
    result_738197525 = nimCopy(result_738197525, {Field0: colontmp__587203827, Field1: colontmp__587203828}, NTI738197518);

  return result_738197525;

}

function escapeCString__dochack_u719(x_p0, x_p0_Idx) {
    var s_587203281 = [];
    Label1: {
      var c_587203282 = 0;
      var iHEX60gensym14_587203831 = 0;
      var nHEX60gensym14_587203832 = ((x_p0[x_p0_Idx]) == null ? 0 : (x_p0[x_p0_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym14_587203831 < nHEX60gensym14_587203832)) break Label3;
            c_587203282 = x_p0[x_p0_Idx].charCodeAt(chckIndx(iHEX60gensym14_587203831, 0, (x_p0[x_p0_Idx]).length - 1));
            switch (c_587203282) {
            case 60:
              nimAddStrStr(s_587203281, [38,108,116,59]);;
              break;
            case 62:
              nimAddStrStr(s_587203281, [38,103,116,59]);;
              break;
            default: 
              addChar(s_587203281, c_587203282);;
              break;
            }
            iHEX60gensym14_587203831 += 1;
          }
      };
    };
    x_p0[x_p0_Idx] = toJSStr(s_587203281);

  
}

function dosearch__dochack_u723(value_p0) {
    var Temporary5;

function HEX3Aanonymous__dochack_u751(a_p0, b_p1) {
  var result_587203324 = 0;

    result_587203324 = subInt(b_p1["Field1"], a_p0["Field1"]);

  return result_587203324;

}

  var result_587203285 = null;

  BeforeRet: {
    if (((db_587203277[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_587203289 = tree__dochack_u114("UL", []);
    result_587203285 = tree__dochack_u114("DIV", []);
    setClass__dochack_u136(result_587203285, "search_results");
    var matches_587203294 = [];
    Label1: {
      var i_587203302 = 0;
      var colontmp__587203818 = 0;
      colontmp__587203818 = (db_587203277[0]).length;
      var i_587203819 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203819 < colontmp__587203818)) break Label3;
            i_587203302 = i_587203819;
            Label4: {
              var c_587203303 = contents_587203278[0][chckIndx(i_587203302, 0, (contents_587203278[0]).length - 1)];
              if (((c_587203303 == "Examples") || (c_587203303 == "PEG construction"))) {
              break Label4;
              }
              
              var tmpTuple_587203304 = fuzzyMatch__fuzzysearch_u16(value_p0, c_587203303);
              var score_587203305 = tmpTuple_587203304["Field0"];
              var matched_587203306 = tmpTuple_587203304["Field1"];
              if (matched_587203306) {
              matches_587203294.push({Field0: db_587203277[0][chckIndx(i_587203302, 0, (db_587203277[0]).length - 1)], Field1: score_587203305});;
              }
              
            };
            i_587203819 = addInt(i_587203819, 1);
          }
      };
    };
    Temporary5 = HEX3Aanonymous__dochack_u751.bind(null); Temporary5.ClP_0 = HEX3Aanonymous__dochack_u751; Temporary5.ClE_0 = null;
    matches_587203294.sort(Temporary5);
    Label6: {
      var i_587203341 = 0;
      var colontmp__587203822 = 0;
      colontmp__587203822 = nimMin((matches_587203294).length, 29);
      var i_587203823 = 0;
      Label7: {
          Label8: while (true) {
          if (!(i_587203823 < colontmp__587203822)) break Label8;
            i_587203341 = i_587203823;
            matches_587203294[chckIndx(i_587203341, 0, (matches_587203294).length - 1)]["Field0"].innerHTML = matches_587203294[chckIndx(i_587203341, 0, (matches_587203294).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString__dochack_u719(matches_587203294[chckIndx(i_587203341, 0, (matches_587203294).length - 1)]["Field0"], "innerHTML");
            add__dochack_u132(ul_587203289, tree__dochack_u114("LI", [matches_587203294[chckIndx(i_587203341, 0, (matches_587203294).length - 1)]["Field0"]]));
            i_587203823 = addInt(i_587203823, 1);
          }
      };
    };
    if ((ul_587203289.childNodes.length == 0)) {
    add__dochack_u132(result_587203285, tree__dochack_u114("B", [text__dochack_u139("no search results")]));
    }
    else {
      add__dochack_u132(result_587203285, tree__dochack_u114("B", [text__dochack_u139("search results")]));
      add__dochack_u132(result_587203285, ul_587203289);
    }
    
  };

  return result_587203285;

}

function hideSearch__dochack_u1042() {
    if (!((oldtoc_587203598[0] == null))) {
    replaceById__dochack_u142("tocRoot", oldtoc_587203598[0]);
    }
    

  
}

function runSearch__dochack_u1046() {
    var elem_587203607 = document.getElementById("searchInput");
    var value_587203608 = elem_587203607.value;
    if (!((value_587203608 == ""))) {
    if ((oldtoc_587203598[0] == null)) {
    oldtoc_587203598[0] = document.getElementById("tocRoot");
    }
    
    var results_587203612 = dosearch__dochack_u723(value_587203608);
    replaceById__dochack_u142("tocRoot", results_587203612);
    }
    else {
    hideSearch__dochack_u1042();
    }
    

  
}

function search() {
    var Temporary1;

    if ((loadIndexFut_587203601[0] == null)) {
    loadIndexFut_587203601[0] = loadIndex__dochack_u896();
    (then__dochack_u1059(loadIndexFut_587203601[0], runSearch__dochack_u1046, null));
    }
    
    if (!((timer_587203599[0] == null))) {
    clearTimeout(timer_587203599[0]);
    }
    
    Temporary1 = runSearch__dochack_u1046.bind(null); Temporary1.ClP_0 = runSearch__dochack_u1046; Temporary1.ClE_0 = null;
    timer_587203599[0] = setTimeout(Temporary1, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre:not(.line-nums)")

      allPreTags.forEach((e) => {

          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")

          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML

          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '')
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"

          div.appendChild(preTag)
          div.appendChild(button)

          e.outerHTML = div.outerHTML

      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })

    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var Temporary2;

function HEX3Aanonymous__dochack_u1127(e_p0) {
    if ((e_p0.key == "/")) {
    e_p0.preventDefault();
    var searchElem_587203689 = document.getElementById("searchInput");
    searchElem_587203689.focus();
    searchElem_587203689.parentElement.scrollIntoView();
    runSearch__dochack_u1046();
    }
    

  
}
var Temporary3;

function HEX3Aanonymous__dochack_u1162(e_p0) {
    hideSearch__dochack_u1042();

  
}
var Temporary4;
var t_587202599 = window.localStorage.getItem("theme");
if ((t_587202599 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_587202599;
}

setTheme(Temporary1);
var alternative_587203235 = [null];
var db_587203277 = [[]];
var contents_587203278 = [[]];
var oldtoc_587203598 = [null];
var timer_587203599 = [null];
var loadIndexFut_587203601 = [null];
Temporary2 = HEX3Aanonymous__dochack_u1127.bind(null); Temporary2.ClP_0 = HEX3Aanonymous__dochack_u1127; Temporary2.ClE_0 = null;
window.addEventListener("keypress", Temporary2, false);
Temporary3 = HEX3Aanonymous__dochack_u1162.bind(null); Temporary3.ClP_0 = HEX3Aanonymous__dochack_u1162; Temporary3.ClE_0 = null;
window.addEventListener("hashchange", Temporary3, false);
copyToClipboard();
Temporary4 = onDOMLoaded.bind(null); Temporary4.ClP_0 = onDOMLoaded; Temporary4.ClE_0 = null;
window.addEventListener("DOMContentLoaded", Temporary4, false);
